### PR TITLE
Update routes.js

### PR DESCRIPTION
**Pull request by lstables**
Changed tab title from uppercase to lowercase

### CODE REVIEW

**Comment by nunomaduro** [comment]
Can you make some screenshots to see the before and after?

**Comment by lstables** [comment]
I can do a before, but not an after as it wouldn't show until it's deployed.

But basically, this.

Screenshot 2020-09-14 at 15 05 33


Would read better as `Vapor UI - queue logs` or maybe uppercase first letter of each word. If not then it's no major, just preference when it comes to tabs that's all ;)

**Comment by taylorotwell** [comment]
If anything I would do Title Case.

**Comment by lstables** [comment]
Yes, Taylor that would be cool if it can, just would look better thats all minor detail :)

**Pull request closed without merging**
